// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: xo.proto

package xo

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldOverride_IndexType int32

const (
	FieldOverride_NONE   FieldOverride_IndexType = 0
	FieldOverride_INDEX  FieldOverride_IndexType = 1
	FieldOverride_UNIQUE FieldOverride_IndexType = 2
)

// Enum value maps for FieldOverride_IndexType.
var (
	FieldOverride_IndexType_name = map[int32]string{
		0: "NONE",
		1: "INDEX",
		2: "UNIQUE",
	}
	FieldOverride_IndexType_value = map[string]int32{
		"NONE":   0,
		"INDEX":  1,
		"UNIQUE": 2,
	}
)

func (x FieldOverride_IndexType) Enum() *FieldOverride_IndexType {
	p := new(FieldOverride_IndexType)
	*p = x
	return p
}

func (x FieldOverride_IndexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldOverride_IndexType) Descriptor() protoreflect.EnumDescriptor {
	return file_xo_proto_enumTypes[0].Descriptor()
}

func (FieldOverride_IndexType) Type() protoreflect.EnumType {
	return &file_xo_proto_enumTypes[0]
}

func (x FieldOverride_IndexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldOverride_IndexType.Descriptor instead.
func (FieldOverride_IndexType) EnumDescriptor() ([]byte, []int) {
	return file_xo_proto_rawDescGZIP(), []int{1, 0}
}

// MessageOverride is an override of default marshalling behaviour of
// protoc-gen-xo.
type MessageOverride struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Create the table without a default primary key.
	Manual bool `protobuf:"varint,1,opt,name=manual,proto3" json:"manual,omitempty"`
	// Ignore the annotated message and not create a table for it.
	Ignore bool `protobuf:"varint,2,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Embeds the message as a JSON instead of creating a new table, whenever
	// referenced.
	EmbedAsJson bool `protobuf:"varint,3,opt,name=embed_as_json,json=embedAsJson,proto3" json:"embed_as_json,omitempty"`
}

func (x *MessageOverride) Reset() {
	*x = MessageOverride{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOverride) ProtoMessage() {}

func (x *MessageOverride) ProtoReflect() protoreflect.Message {
	mi := &file_xo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOverride.ProtoReflect.Descriptor instead.
func (*MessageOverride) Descriptor() ([]byte, []int) {
	return file_xo_proto_rawDescGZIP(), []int{0}
}

func (x *MessageOverride) GetManual() bool {
	if x != nil {
		return x.Manual
	}
	return false
}

func (x *MessageOverride) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

func (x *MessageOverride) GetEmbedAsJson() bool {
	if x != nil {
		return x.EmbedAsJson
	}
	return false
}

// FieldOverride is an override of default marshalling behaviour of
// protoc-gen-xo.
type FieldOverride struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Marks the index type for the field.
	Index FieldOverride_IndexType `protobuf:"varint,1,opt,name=index,proto3,enum=xo.options.FieldOverride_IndexType" json:"index,omitempty"`
	// Ignore the annotated field and not create a column and/or associated
	// tables for it.
	Ignore bool `protobuf:"varint,2,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Embeds the field as a JSON instead of creating a new table.
	EmbedAsJson bool `protobuf:"varint,3,opt,name=embed_as_json,json=embedAsJson,proto3" json:"embed_as_json,omitempty"`
	// SQL Expression for the default value for the annotated field.
	DefaultValue string `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
}

func (x *FieldOverride) Reset() {
	*x = FieldOverride{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOverride) ProtoMessage() {}

func (x *FieldOverride) ProtoReflect() protoreflect.Message {
	mi := &file_xo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOverride.ProtoReflect.Descriptor instead.
func (*FieldOverride) Descriptor() ([]byte, []int) {
	return file_xo_proto_rawDescGZIP(), []int{1}
}

func (x *FieldOverride) GetIndex() FieldOverride_IndexType {
	if x != nil {
		return x.Index
	}
	return FieldOverride_NONE
}

func (x *FieldOverride) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

func (x *FieldOverride) GetEmbedAsJson() bool {
	if x != nil {
		return x.EmbedAsJson
	}
	return false
}

func (x *FieldOverride) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

var file_xo_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.MessageOptions)(nil),
		ExtensionType: (*MessageOverride)(nil),
		Field:         1143,
		Name:          "xo.options.msg_overrides",
		Tag:           "bytes,1143,opt,name=msg_overrides",
		Filename:      "xo.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*FieldOverride)(nil),
		Field:         1143,
		Name:          "xo.options.field_overrides",
		Tag:           "bytes,1143,opt,name=field_overrides",
		Filename:      "xo.proto",
	},
}

// Extension fields to descriptor.MessageOptions.
var (
	// optional xo.options.MessageOverride msg_overrides = 1143;
	E_MsgOverrides = &file_xo_proto_extTypes[0]
)

// Extension fields to descriptor.FieldOptions.
var (
	// optional xo.options.FieldOverride field_overrides = 1143;
	E_FieldOverrides = &file_xo_proto_extTypes[1]
)

var File_xo_proto protoreflect.FileDescriptor

var file_xo_proto_rawDesc = []byte{
	0x0a, 0x08, 0x78, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x78, 0x6f, 0x2e, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x61, 0x6e, 0x75, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6d, 0x61, 0x6e,
	0x75, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x65,
	0x6d, 0x62, 0x65, 0x64, 0x5f, 0x61, 0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x41, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x22,
	0xd9, 0x01, 0x0a, 0x0d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64,
	0x65, 0x12, 0x39, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x23, 0x2e, 0x78, 0x6f, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x2e, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x67,
	0x6e, 0x6f, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x5f, 0x61, 0x73,
	0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x65, 0x6d, 0x62,
	0x65, 0x64, 0x41, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2c, 0x0a,
	0x09, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x44, 0x45, 0x58, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x49, 0x51, 0x55, 0x45, 0x10, 0x02, 0x3a, 0x62, 0x0a, 0x0d, 0x6d,
	0x73, 0x67, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xf7, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x78, 0x6f, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64,
	0x65, 0x52, 0x0c, 0x6d, 0x73, 0x67, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x73, 0x3a,
	0x62, 0x0a, 0x0f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64,
	0x65, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xf7, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x78, 0x6f, 0x2e, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x76, 0x65, 0x72, 0x72,
	0x69, 0x64, 0x65, 0x52, 0x0e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69,
	0x64, 0x65, 0x73, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x78, 0x6f, 0x2f, 0x65, 0x63, 0x6f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x78, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xo_proto_rawDescOnce sync.Once
	file_xo_proto_rawDescData = file_xo_proto_rawDesc
)

func file_xo_proto_rawDescGZIP() []byte {
	file_xo_proto_rawDescOnce.Do(func() {
		file_xo_proto_rawDescData = protoimpl.X.CompressGZIP(file_xo_proto_rawDescData)
	})
	return file_xo_proto_rawDescData
}

var file_xo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xo_proto_goTypes = []interface{}{
	(FieldOverride_IndexType)(0),      // 0: xo.options.FieldOverride.IndexType
	(*MessageOverride)(nil),           // 1: xo.options.MessageOverride
	(*FieldOverride)(nil),             // 2: xo.options.FieldOverride
	(*descriptor.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptor.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_xo_proto_depIdxs = []int32{
	0, // 0: xo.options.FieldOverride.index:type_name -> xo.options.FieldOverride.IndexType
	3, // 1: xo.options.msg_overrides:extendee -> google.protobuf.MessageOptions
	4, // 2: xo.options.field_overrides:extendee -> google.protobuf.FieldOptions
	1, // 3: xo.options.msg_overrides:type_name -> xo.options.MessageOverride
	2, // 4: xo.options.field_overrides:type_name -> xo.options.FieldOverride
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xo_proto_init() }
func file_xo_proto_init() {
	if File_xo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOverride); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOverride); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_xo_proto_goTypes,
		DependencyIndexes: file_xo_proto_depIdxs,
		EnumInfos:         file_xo_proto_enumTypes,
		MessageInfos:      file_xo_proto_msgTypes,
		ExtensionInfos:    file_xo_proto_extTypes,
	}.Build()
	File_xo_proto = out.File
	file_xo_proto_rawDesc = nil
	file_xo_proto_goTypes = nil
	file_xo_proto_depIdxs = nil
}
